// Token data from CSV - embedded for Edge Runtime compatibility
export const tokenList = [
  { name: 'Aptos', ticker: 'APT', startDate: 'March 21, 2025', hasToken: true },
  { name: 'Berachain', ticker: 'BERA', startDate: 'December 2024', hasToken: true },
  { name: 'Injective', ticker: 'INJ', startDate: 'June 3, 2025', hasToken: true },
  { name: 'Kaia', ticker: 'KAIA', startDate: 'April 8, 2025', hasToken: true },
  { name: 'MANTRA', ticker: 'OM', startDate: 'April 8, 2025', hasToken: true },
  { name: 'Movement', ticker: 'MOVE', startDate: 'January 6, 2025', hasToken: true },
  { name: 'Near', ticker: 'NEAR', startDate: 'May 27, 2025', hasToken: true },
  { name: 'PEAQ', ticker: 'PEAQ', startDate: 'June 18, 2025', hasToken: true },
  { name: 'Polkadot', ticker: 'DOT', startDate: 'February 13, 2025', hasToken: true },
  { name: 'Sei', ticker: 'SEI', startDate: 'January 8, 2025', hasToken: true },
  { name: 'Sonic', ticker: 'S', startDate: 'June 27, 2025', hasToken: true },
  { name: 'Story', ticker: 'STORY', startDate: 'January 7, 2025', hasToken: true },
  { name: 'XION', ticker: 'XION', startDate: 'November 28, 2025', hasToken: true },
  { name: 'CreatorBid', ticker: 'BID', startDate: 'June 13, 2025', hasToken: true },
  { name: 'Newton', ticker: 'NEWT', startDate: 'May 17, 2025', hasToken: true },
  { name: 'Virtuals Protocol', ticker: 'VIRTUAL', startDate: 'May 13, 2025', hasToken: true },
  { name: 'Warden Protocol', ticker: 'WARD', startDate: 'June 18, 2025', hasToken: true },
  { name: 'Wayfinder', ticker: 'PROMPT', startDate: 'April 4, 2025', hasToken: true },
  { name: 'ANIME', ticker: 'ANIME', startDate: 'January 9, 2025', hasToken: true },
  { name: 'Boop', ticker: 'BOOP', startDate: 'May 1, 2025', hasToken: true },
  { name: 'PENGU', ticker: 'PENGU', startDate: 'May 5, 2025', hasToken: true },
  { name: 'Corn', ticker: 'CORN', startDate: 'December 2024', hasToken: true },
  { name: 'GOAT Network', ticker: 'GOATED', startDate: 'June 17, 2025', hasToken: true },
  { name: 'Arbitrum', ticker: 'ARB', startDate: 'May 27, 2025', hasToken: true },
  { name: 'Katana', ticker: 'KAT', startDate: 'June 10, 2025', hasToken: true },
  { name: 'Mantle', ticker: 'MNT', startDate: 'May 18, 2025', hasToken: true },
  { name: 'Polygon', ticker: 'MATIC', startDate: 'July 29, 2025', hasToken: true },
  { name: 'SOON', ticker: 'SOON', startDate: 'May 12, 2025', hasToken: true },
  { name: 'Falcon Finance', ticker: 'FF', startDate: 'August 5, 2025', hasToken: true },
  { name: 'Frax', ticker: 'FRAX', startDate: 'Early 2025', hasToken: true },
  { name: 'Huma', ticker: 'HUMA', startDate: 'May 19, 2025', hasToken: true },
  { name: 'Orderly', ticker: 'ORDER', startDate: 'June 24, 2025', hasToken: true },
  { name: 'Pyth', ticker: 'PYTH', startDate: 'March 11, 2025', hasToken: true },
  { name: 'Starknet', ticker: 'STRK', startDate: 'Early 2025', hasToken: true },
  { name: 'Zcash', ticker: 'ZEC', startDate: 'June 6, 2025', hasToken: true },
  { name: 'Humanity Protocol', ticker: 'H', startDate: 'May 28, 2025', hasToken: true },
  { name: 'dYdX', ticker: 'DYDX', startDate: 'May 14, 2025', hasToken: true },
  { name: 'Kaito', ticker: 'KAITO', startDate: 'December 2024', hasToken: true },
  { name: 'IQ', ticker: 'IQ', startDate: 'April 9, 2025', hasToken: true },
  { name: 'UXLINK', ticker: 'UXLINK', startDate: 'June 12, 2025', hasToken: true },
  { name: 'Defi App', ticker: 'DEFI', startDate: 'March 4, 2025', hasToken: true },
  { name: 'MapleStory Universe', ticker: 'NXPC', startDate: 'May 13, 2025', hasToken: true },
  { name: 'Sophon', ticker: 'SOPH', startDate: 'March 31, 2025', hasToken: true },
  { name: 'Initia', ticker: 'INIT', startDate: 'March 27, 2025', hasToken: true },
  { name: 'Skate', ticker: 'SKATE', startDate: 'February 25, 2025', hasToken: true },
];

export function getCoinIdFromTicker(ticker: string): string {
  const tickerMap: Record<string, string> = {
    'APT': 'aptos',
    'BERA': 'berachain',
    'INJ': 'injective-protocol',
    'KAIA': 'kaia',
    'OM': 'mantra-dao',
    'MOVE': 'movement',
    'NEAR': 'near',
    'PEAQ': 'peaq',
    'DOT': 'polkadot',
    'SEI': 'sei-network',
    'S': 'sonic',
    'STORY': 'story',
    'XION': 'xion',
    'BID': 'creatorbid',
    'NEWT': 'newton',
    'VIRTUAL': 'virtuals-protocol',
    'WARD': 'warden',
    'PROMPT': 'wayfinder',
    'ANIME': 'anime',
    'BOOP': 'boop',
    'PENGU': 'pengu',
    'CORN': 'corn',
    'GOATED': 'goat-network',
    'ARB': 'arbitrum',
    'KAT': 'katana-inu',
    'MNT': 'mantle',
    'MATIC': 'matic-network',
    'SOON': 'soon',
    'FF': 'falcon-finance',
    'FRAX': 'frax',
    'HUMA': 'huma-finance',
    'ORDER': 'orderly-network',
    'PYTH': 'pyth-network',
    'STRK': 'starknet',
    'ZEC': 'zcash',
    'H': 'humanity-protocol',
    'DYDX': 'dydx',
    'KAITO': 'kaito',
    'IQ': 'everipedia',
    'UXLINK': 'uxlink',
    'DEFI': 'defi-app',
    'NXPC': 'maplestory-universe',
    'SOPH': 'sophon',
    'INIT': 'initia',
    'SKATE': 'skate'
  };
  
  return tickerMap[ticker.toUpperCase()] || ticker.toLowerCase();
}

